set fallback := true
set windows-shell := ["gnu-tk", "-i", "-c"]

# Show the help for this justfile
@help:
    just --list

pack: clean
    mkdir output .obj
    cd build; chmod +x *.sh; ./pack.sh

clean:
    rm -rf output .obj
