set windows-shell := ["gnu-tk", "-i", "-c"]

@help:
    just --list

# Format source code
[group("development")]
format:
    deno fmt *.md
    cd guides/getting-started/windows; just format

# Check source code
[group("development")]
check:
    cd guides/getting-started/windows; just check
